# Default values for epso14-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullname: keycloak
#CHANGEME
labels:
  app: keycloak
#autoscaling.enable: false
replicaCount: 1
selectorLabels: 
  app: keycloak

keycloak:
  name: keycloak
  image:
    repository: jboss/keycloak
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "15.1.1"
  args: 
    - "-b 0.0.0.0"
    - "-Dkeycloak.profile.feature.upload_scripts=enabled"
  env:
  - name: KEYCLOAK_USER
    value: "admin"
  - name: KEYCLOAK_PASSWORD
    value: "admin"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  ports:
  - name: http
    containerPort: 8080
  - name: https
    containerPort: 8443
  readinessProbe:
    httpGet:
      path: /auth/realms/master
      port: 8080
  volumeMounts:
  - name: tls-keys
    mountPath: "/etc/x509/https"
    readOnly: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
