apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "epso14-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "epso14-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.keycloak.name }}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          args:
            {{- toYaml .Values.keycloak.args | nindent 12 }}
          env:
            {{- toYaml .Values.keycloak.env | nindent 12 }}
          ports:
            {{- toYaml .Values.keycloak.ports | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.keycloak.readinessProbe | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.keycloak.volumeMounts | nindent 12}}
          {{- if .Values.keycloak.image.pullPolicy}}
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          {{-- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
